title   BLUR OS
linux   /vmlinuz-linux-lts
initrd  /initramfs-linux-lts.img
options root=UUID=CHANGEME_ROOT_UUID rw \
        lsm=landlock,lockdown,yama,integrity,apparmor,bpf \
        apparmor=1 security=apparmor \
        zswap.enabled=1 zswap.compressor=zstd zswap.zpool=z3fold \
        quiet splash loglevel=3 rd.udev.log_level=3 \
        mitigations=auto LANG=en_US.UTF-8
