# preload configuration for NiyasOS
# Preload learns which applications you use most and preloads them into RAM

[system]
cycle = 30          # seconds between scans
logfile = /var/log/preload.log
loglevel = 1

[model]
memtotal = 0
memfree = 0
memcached = 0
mapprefix = /usr
exeprefix = /usr
minsize = 2000000   # min size for tracking: 2MB
